[workspace]
resolver = "3"
members = [ "lex", "ast", "cli" , "parse", "assembly-ast", "tests", "test-generator" ]

# Used since insta recommends building it in release mode for faster tests
[profile.dev.package]
insta.opt-level = 3
