[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
lex = { path = "../lex" }
parse = { path = "../parse" }
assembly-ast = { path = "../assembly-ast/" }
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
