[package]
name = "lex"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"

[dev-dependencies]
insta = "1.43.1"

# Used since insta recommends building it in release mode for faster tests
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
